### ISSUE TITLE
Question about key-value

### ISSUE THREAD

**Issue by EricOuellet2** [dmcmanam/bbst-showdown#1]
I'm very curious. I wonder why do you use map (key-value) instead of working solely with values that would implements IComparable. In which situation it would be useful to separate the key from the value. I thought that the sorting attributes (the key) would always be inferred from the value or a part of it. There should be a logical link between the value and its key. Why not just using an interface IComparable on values?

**Comment by dmcmanam** [comment]
I'm following the NavigableMap interface in this project to easily compare performance with the JDK's TreeMap implementation.
https://docs.oracle.com/javase/8/docs/api/java/util/NavigableMap.html

The same AVL code could be applied to TreeSet or other implementations.
